name = "cloudcang-booking-template"
main = "src/index.js"
compatibility_date = "2026-09-13"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "cloudcang-booking-template"
database_id = "REPLACE_WITH_YOUR_OWN_D1_DATABASE_ID"

[triggers]
crons = ["*/10 * * * *"]
